databases:
  - name: gabbler
    databaseName: gabbler
    user: amer

services:
  - type: web
    name: gabbler
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gabbler
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false